[package]
name = "de5000-tauri"
version = "1.0.0-alpha.11"
edition = "2021"
license = "MIT"

[lib]
name = "de5000_tauri_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.11", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = "4"
ntfy-rs = { package = "ntfy-server-rs", git = "https://github.com/Arcturus808/ntfy-rs", rev = "002aa79a0147d7ffef5236792e0e75894093ef69", default-features = false }
local-ip-address = "0.6"
tokio = { version = "1", features = ["time"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"
